require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.1
  Exclude:
    - "config.ru"
    - "Rakefile"
    - "config/**/*"
    - "bin/*"
    - "test/**/*"
    - "spec/**/"
    - "db/**/*"

  NewCops: enable

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
