common: &common
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *common
  adapter: postgres
  database: <%= ENV.fetch("DATABASE_URL") %>

test:
  <<: *common
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgres
  <<: *common
  database: <%= ENV.fetch("DATABASE_URL") %>
